create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  legacy_user_id integer unique,
  email text not null unique,
  name text,
  role text not null default 'user' check (role in ('user', 'admin')),
  status text not null default 'active' check (status in ('active', 'banned')),
  sample_personal_topic_seeded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references public.profiles(id) on delete cascade,
  current_xp integer not null default 0,
  level integer not null default 1,
  current_streak integer not null default 0,
  last_study_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  description text,
  thumbnail_url text,
  language text not null default 'en',
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.topics (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete cascade,
  owner_user_id uuid references public.profiles(id) on delete cascade,
  slug text,
  title text not null,
  description text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.flashcards (
  id bigint generated by default as identity primary key,
  topic_id bigint not null references public.topics(id) on delete cascade,
  external_id text,
  word text not null,
  transcription text,
  meaning text not null,
  word_type text,
  example text,
  example_vi text,
  language text not null default 'en',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_word_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  flashcard_id bigint not null references public.flashcards(id) on delete cascade,
  is_remembered boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_user_word_progress unique (user_id, flashcard_id)
);

create table if not exists public.srs_reviews (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  flashcard_id bigint not null references public.flashcards(id) on delete cascade,
  interval_days integer not null default 1,
  ef numeric(4, 2) not null default 2.50,
  repetition integer not null default 0,
  next_review_date date not null,
  last_reviewed_at timestamptz,
  fail_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_srs_reviews_user_flashcard unique (user_id, flashcard_id)
);

create table if not exists public.toeic_tests (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.toeic_question_groups (
  id bigint generated by default as identity primary key,
  test_id bigint not null references public.toeic_tests(id) on delete cascade,
  part integer not null check (part between 1 and 7),
  audio_url text,
  image_url text,
  passage_text text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.toeic_questions (
  id bigint generated by default as identity primary key,
  test_id bigint not null references public.toeic_tests(id) on delete cascade,
  group_id bigint references public.toeic_question_groups(id) on delete cascade,
  question_number integer not null,
  part integer not null check (part between 1 and 7),
  question_text text,
  options jsonb not null,
  correct_answer text not null,
  explanation text,
  audio_url text,
  image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.toeic_test_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  test_id bigint not null references public.toeic_tests(id) on delete cascade,
  reading_score integer not null default 0,
  listening_score integer not null default 0,
  total_score integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.support_tickets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  type text not null default 'gop-y' check (type in ('gop-y', 'bao-loi')),
  title text not null,
  content text not null,
  status text not null default 'pending' check (status in ('pending', 'agreed', 'rejected')),
  reviewer_id uuid references public.profiles(id) on delete set null,
  source_page text,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.vocab_activity_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  mode text not null check (mode in ('flashcard', 'quiz', 'listen', 'typing', 'match', 'flappy-bird')),
  created_at timestamptz not null default now()
);
