-- DANGEROUS RESET SCRIPT
-- This script drops and recreates the entire public schema.
-- Use only on a fresh/test database or after you have taken a backup and confirmed
-- that you want to lose all existing data in public schema.
--
-- This script intentionally does NOT touch:
-- - auth schema
-- - storage schema
-- - extensions outside public
--
-- Recommended execution order:
-- 1) backup
-- 2) run this script on Supabase SQL editor or migration runner
-- 3) seed minimal data
-- 4) verify login, courses, custom topics, RLS, and shares

drop schema if exists public cascade;

create schema public;

grant usage on schema public to postgres, anon, authenticated, service_role;
grant create on schema public to postgres, service_role;

alter default privileges in schema public
grant select, insert, update, delete on tables to postgres, authenticated, service_role;

alter default privileges in schema public
grant usage, select on sequences to postgres, authenticated, service_role;

create extension if not exists pgcrypto with schema public;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  legacy_user_id integer unique,
  email text not null unique,
  name text,
  role text not null default 'user' check (role in ('user', 'admin')),
  status text not null default 'active' check (status in ('active', 'banned')),
  sample_personal_topic_seeded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.user_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references public.profiles(id) on delete cascade,
  current_xp integer not null default 0,
  level integer not null default 1,
  current_streak integer not null default 0,
  last_study_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.courses (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  description text,
  thumbnail_url text,
  language text not null default 'en',
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.topics (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete cascade,
  owner_user_id uuid references public.profiles(id) on delete cascade,
  slug text,
  title text not null,
  description text,
  language text not null default 'en',
  shared_from_topic_id bigint references public.topics(id) on delete set null,
  is_custom boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.flashcards (
  id bigint generated by default as identity primary key,
  topic_id bigint not null references public.topics(id) on delete cascade,
  external_id text,
  word text not null,
  transcription text,
  meaning text not null,
  word_type text,
  example text,
  example_vi text,
  language text not null default 'en',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.user_word_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  flashcard_id bigint not null references public.flashcards(id) on delete cascade,
  is_remembered boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_user_word_progress unique (user_id, flashcard_id)
);

create table public.srs_reviews (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  flashcard_id bigint not null references public.flashcards(id) on delete cascade,
  interval_days integer not null default 1,
  ef numeric(4, 2) not null default 2.50,
  repetition integer not null default 0,
  next_review_date date not null,
  last_reviewed_at timestamptz,
  fail_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_srs_reviews_user_flashcard unique (user_id, flashcard_id)
);

create table public.toeic_tests (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.toeic_question_groups (
  id bigint generated by default as identity primary key,
  test_id bigint not null references public.toeic_tests(id) on delete cascade,
  part integer not null check (part between 1 and 7),
  audio_url text,
  image_url text,
  passage_text text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.toeic_questions (
  id bigint generated by default as identity primary key,
  test_id bigint not null references public.toeic_tests(id) on delete cascade,
  group_id bigint references public.toeic_question_groups(id) on delete cascade,
  question_number integer not null,
  part integer not null check (part between 1 and 7),
  question_text text,
  options jsonb not null,
  correct_answer text not null,
  explanation text,
  audio_url text,
  image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.toeic_test_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  test_id bigint not null references public.toeic_tests(id) on delete cascade,
  reading_score integer not null default 0,
  listening_score integer not null default 0,
  total_score integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.support_tickets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  type text not null default 'gop-y' check (type in ('gop-y', 'bao-loi')),
  title text not null,
  content text not null,
  status text not null default 'pending' check (status in ('pending', 'agreed', 'rejected')),
  reviewer_id uuid references public.profiles(id) on delete set null,
  source_page text,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.vocab_activity_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  mode text not null check (mode in ('flashcard', 'quiz', 'listen', 'typing', 'match', 'flappy-bird')),
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'admin'
      and status = 'active'
  );
$$;

alter table public.profiles enable row level security;
alter table public.user_progress enable row level security;
alter table public.courses enable row level security;
alter table public.topics enable row level security;
alter table public.flashcards enable row level security;
alter table public.user_word_progress enable row level security;
alter table public.srs_reviews enable row level security;
alter table public.toeic_tests enable row level security;
alter table public.toeic_question_groups enable row level security;
alter table public.toeic_questions enable row level security;
alter table public.toeic_test_records enable row level security;
alter table public.support_tickets enable row level security;
alter table public.vocab_activity_logs enable row level security;

create policy profiles_select_own_or_admin on public.profiles
for select using (id = auth.uid() or public.is_admin());

create policy profiles_update_own_or_admin on public.profiles
for update using (id = auth.uid() or public.is_admin())
with check (id = auth.uid() or public.is_admin());

create policy user_progress_select_own_or_admin on public.user_progress
for select using (user_id = auth.uid() or public.is_admin());

create policy user_progress_update_own_or_admin on public.user_progress
for update using (user_id = auth.uid() or public.is_admin())
with check (user_id = auth.uid() or public.is_admin());

create policy courses_public_read on public.courses
for select using (true);

create policy courses_admin_write on public.courses
for all using (public.is_admin())
with check (public.is_admin());

create policy topics_select_policy on public.topics
for select using (
  owner_user_id is null
  or owner_user_id = auth.uid()
  or public.is_admin()
);

create policy topics_insert_policy on public.topics
for insert with check (
  public.is_admin()
  or owner_user_id = auth.uid()
);

create policy topics_update_policy on public.topics
for update using (
  public.is_admin()
  or owner_user_id = auth.uid()
)
with check (
  public.is_admin()
  or owner_user_id = auth.uid()
);

create policy topics_delete_policy on public.topics
for delete using (
  public.is_admin()
  or owner_user_id = auth.uid()
);

create policy flashcards_select_policy on public.flashcards
for select using (
  exists (
    select 1
    from public.topics t
    where t.id = flashcards.topic_id
      and (
        t.owner_user_id is null
        or t.owner_user_id = auth.uid()
        or public.is_admin()
      )
  )
);

create policy flashcards_insert_policy on public.flashcards
for insert with check (
  exists (
    select 1
    from public.topics t
    where t.id = flashcards.topic_id
      and (public.is_admin() or t.owner_user_id = auth.uid())
  )
);

create policy flashcards_update_policy on public.flashcards
for update using (
  exists (
    select 1
    from public.topics t
    where t.id = flashcards.topic_id
      and (public.is_admin() or t.owner_user_id = auth.uid())
  )
)
with check (
  exists (
    select 1
    from public.topics t
    where t.id = flashcards.topic_id
      and (public.is_admin() or t.owner_user_id = auth.uid())
  )
);

create policy flashcards_delete_policy on public.flashcards
for delete using (
  exists (
    select 1
    from public.topics t
    where t.id = flashcards.topic_id
      and (public.is_admin() or t.owner_user_id = auth.uid())
  )
);

create policy user_word_progress_policy on public.user_word_progress
for all using (user_id = auth.uid() or public.is_admin())
with check (user_id = auth.uid() or public.is_admin());

create policy srs_reviews_policy on public.srs_reviews
for all using (user_id = auth.uid() or public.is_admin())
with check (user_id = auth.uid() or public.is_admin());

create policy toeic_tests_public_read on public.toeic_tests
for select using (true);

create policy toeic_tests_admin_write on public.toeic_tests
for all using (public.is_admin())
with check (public.is_admin());

create policy toeic_question_groups_public_read on public.toeic_question_groups
for select using (true);

create policy toeic_question_groups_admin_write on public.toeic_question_groups
for all using (public.is_admin())
with check (public.is_admin());

create policy toeic_questions_public_read on public.toeic_questions
for select using (true);

create policy toeic_questions_admin_write on public.toeic_questions
for all using (public.is_admin())
with check (public.is_admin());

create policy toeic_test_records_policy on public.toeic_test_records
for all using (user_id = auth.uid() or public.is_admin())
with check (user_id = auth.uid() or public.is_admin());

create policy support_tickets_select_policy on public.support_tickets
for select using (user_id = auth.uid() or public.is_admin());

create policy support_tickets_insert_policy on public.support_tickets
for insert with check (user_id = auth.uid() or public.is_admin());

create policy support_tickets_update_policy on public.support_tickets
for update using (public.is_admin())
with check (public.is_admin());

create policy vocab_activity_logs_policy on public.vocab_activity_logs
for all using (user_id = auth.uid() or public.is_admin())
with check (user_id = auth.uid() or public.is_admin());

create unique index uq_profiles_legacy_user_id
  on public.profiles (legacy_user_id)
  where legacy_user_id is not null;

create index idx_user_progress_user_id on public.user_progress (user_id);
create index idx_courses_sort_order on public.courses (sort_order);
create index idx_topics_course_id on public.topics (course_id);
create index idx_topics_owner_user_id on public.topics (owner_user_id);
create unique index uq_topics_owner_slug on public.topics (owner_user_id, slug)
  where slug is not null;
create index idx_topics_shared_from_topic_id on public.topics (shared_from_topic_id);
create index idx_flashcards_topic_id on public.flashcards (topic_id);
create index idx_user_word_progress_user_id on public.user_word_progress (user_id);
create index idx_user_word_progress_flashcard_id on public.user_word_progress (flashcard_id);
create index idx_srs_reviews_user_id on public.srs_reviews (user_id);
create index idx_srs_reviews_next_review_date on public.srs_reviews (next_review_date);
create index idx_toeic_question_groups_test_part on public.toeic_question_groups (test_id, part);
create index idx_toeic_questions_test_part on public.toeic_questions (test_id, part);
create index idx_toeic_test_records_user_id on public.toeic_test_records (user_id);
create index idx_support_tickets_user_id on public.support_tickets (user_id);
create index idx_vocab_activity_logs_user_id_created_at on public.vocab_activity_logs (user_id, created_at desc);
